apiVersion: v2
name: argocd-renderer
description: ArgoCD-based manifest rendering service (repo-server only, no apply/sync)
type: application
version: 9.3.6
appVersion: "v3.2.6"
keywords:
  - argocd
  - kubernetes
  - helm
  - kustomize
  - manifest
  - rendering
maintainers:
  - name: argocd-renderer
dependencies:
  - name: argo-cd
    version: 9.3.6
    repository: https://argoproj.github.io/argo-helm
